name: Build and Upload Release
 
on: 
 workflow_dispatch:
   inputs:
     release_tag:
        description: 'Release Tag'     
        required: true
        default: '1.0.0'

jobs:
  create-release:
   runs-on: ubuntu-20.04
   
   steps:
    - name: Create a Release
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag
        tag_name: ${{ github.event.inputs.release_tag }}
        # The name of the release. For example, `Release v1.0.1`
        release_name: ${{ github.event.inputs.release_tag }}
    - shell: bash
      run: |
        expr "${{ steps.create_release.outputs.upload_url }}" > upload_url.txt
    - name: Upload URL
      uses: actions/upload-artifact@v2
      with:
        name: upload_url
        path: upload_url.txt
  
  build-gui:
    runs-on: windows-latest
    needs: [create-release]
    env:
     ACTIONS_ALLOW_UNSECURE_COMMANDS: true
 
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore Dependencies
      run: dotnet restore InstallerAnalyzer
    - name: Build Windows GUI
      run: dotnet publish InstallerAnalyzer -p:PublishProfile=Windows -p:DebugType=None -p:DebugSymbols=false
    
    - name: Download Ffmpeg To Workspace
      # You may pin to the exact commit or the version.
      # uses: carlosperate/download-file-action@e85e0aa6262f13571d17a4a39687b26981c583dc
      uses: carlosperate/download-file-action@v1.0.3
      with:
        # URL of the file to download
        file-url: https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip
        # New filename to rename the downloaded file
        file-name: ffmpeg.zip
        
    - name: Bundle Ffmpeg
      run: tar xfz ffmpeg.zip --strip-components=1; copy bin/ffmpeg.exe InstallerAnalyzer/bin/Release/net6.0-windows/publish/win-x64/ffmpeg.exe
      
    - name: Zip Windows GUI Release Asset
      uses: vimtor/action-zip@v1
      with:
        files: "TwitchDownloaderWPF/bin/Release/net6.0-windows/publish/win-x64"
        dest: InstallerAnalyzer-${{ github.event.inputs.release_tag }}-Windows-x64.zip
    
    - name: Download URL
      uses: actions/download-artifact@v2
      with:
        name: upload_url
        
    - name: Read URL
      id: url
      uses: juliangruber/read-file-action@74dc4b4435b60f96f84bcba916659c779f46ba0a
      with:
        path: upload_url.txt
        
    - name: Upload Windows GUI Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.url.outputs.content }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: InstallerAnalyzer-${{ github.event.inputs.release_tag }}-Windows-x64.zip
        asset_name: InstallerAnalyzer-${{ github.event.inputs.release_tag }}-Windows-x64.zip
        asset_content_type: application/zip
